name: main

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Set Python version
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - uses: actions/checkout@v2

      - run: python -m pip install --upgrade pip setuptools
      - run: python -m pip install pipenv
      - run: pipenv install -d

      - run: pipenv run lint

  commit-watch:
    runs-on: ubuntu-latest
    if: contains(github.event_name, 'pull_request')
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - run: npx @eqworks/commit-watch -b ${{ github.event.pull_request.base.sha }} -h ${{ github.event.pull_request.head.sha }} -v

  scan-env:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - run: npx @eqworks/scan-env --strict
